travis:
  secure:
    BINSTAR_TOKEN: WkNfbKrLM2Ip5ziU76VonPl9zS+pPN7YRb7ao0YvNpUc78tWYw0CPv0IyMHPy/SpmOQHB4lfSkB2BXwvDHTkR0xBZNspgM2s6tgIiwjCnkYd9h9Z2TfV1vpAVVmiv9WMFmOlLk0/bb7Tcdt98mSYjFoLCngFoJ5pHqMucCoqkpmfrfOYWmJrkBFdZacB1jP7jzFgIqTv8uF4c8N57pPaRXundrjukEG0cnMUiI8Kp4rdMvCna710UNNx+0HO7YS1p6P73x6C4s6YBDJDwkeI5Tfas7vzhbesKBF2K/oPnTwzBmJuVoLF+I2QTd9HO/y73Use7lZcsVRHxnQhZb+uP8Fz+dPCiY26JFW3VAuJn+BI4yNp13T5uCqA7oH9hO880bVMtT9dFBT/Vg7LbOBAK81y1ca7me3By8Q6hrJ3rY3q+Exg1UIa7vLadjIQJJEIa/kOO/WumZMn0G62/jGrtPXMqiSQiVb7YjCTquzfOPaLGIZt8GW7fBBhP7gdsnfxn98N7GXVE2uqIk/M7zGQJrAwPa+q66svc5lU9o/6ABmja8PkA3egkel91DAxanGac4eeGeBwLQySkGztKY0y3v4gSrssqxxGomCT/q05h3EQ3EWdckKcwqYWfvPJZZufPXgdkp3yz0yFRk34ZaIbHUgzG2yxugbw158294iFRg4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
