appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mVd4aDQwi2Zs1f74VyCGFBoPoQ5jmHlxL40mVaHxFgB4tQuna/fDfLmrhpAYbV14t59evkutiU4LGaPDub9d0GqxCFiL8/s6QqebNf+B+u8z/LxToKwJ3s+TB82PeDneZiZS5jMnR0LOxU7uQqMCGDACJdiYS7QmoC9e/HTBWCj34YhTutNTdU73w/TFjqqtCjP2MZdG1bQwCG86gsuRw9dOm9KICAfVsPUqDF3XJbLzREDRJuKutJ+khWXy4fLUb/XB45sK8OiRMkHbqjRvEA/eblN4wWKs+1j6lyy0doCoCJj07tQZlDLhyjOOeW05ew1KcBBc3QXSBljMSYEDdB/XdT2ZfhbGjZ7fThsnDU41hNg7s7ocGQCTwYYx4km4aZwcUEkOnaPfIDi+TaRelQNm6Ic9bYal+Fa82E0Za+fVYVL0oAQXmMn19JC/yliiHixunZ3dnnAU68ZNvtP7aLwmYG3xdTS4xDGRz/uYDgVGi/V9jPqr0yNITCWQXBGYqHFq7wMel1XnCIFbWrPW4H6GjuTRznjsXa9wb84R5HViIM+RTn9Kwrp7tAjhjRg/XCEhgAbUEKyY4nGg9gVs8EkkkUuDcYI6oyx1utwVsXDH9NYOpTtzqcg/yNcyPXy2hRb6OqtNrbQf5ij63sFFfM1QObIAzRmeX3cX1vZ6nio=}
bot:
  automerge: true
